// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _14CodeFirstEF.Models;

#nullable disable

namespace _14CodeFirstEF.Migrations
{
    [DbContext(typeof(DACDbContext))]
    [Migration("20241228051001_AddEmployeeMigration")]
    partial class AddEmployeeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_14CodeFirstEF.Models.Employee", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"), 1L, 1);

                    b.Property<string>("EAddress")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EAddress");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EName");

                    b.Property<int>("ESalary")
                        .HasColumnType("int")
                        .HasColumnName("ESalary");

                    b.HasKey("EId");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
